[2022-03-27 04:08:23,738] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2022-03-27T04:03:48.472709+00:00 [queued]>
[2022-03-27 04:08:23,785] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2022-03-27T04:03:48.472709+00:00 [queued]>
[2022-03-27 04:08:23,787] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 04:08:23,788] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-03-27 04:08:23,791] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 04:08:23,891] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-03-27 04:03:48.472709+00:00
[2022-03-27 04:08:23,949] {standard_task_runner.py:52} INFO - Started process 1470 to run task
[2022-03-27 04:08:24,000] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2022-03-27T04:03:48.472709+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp8z41m7oe', '--error-file', '/tmp/tmpb4als18o']
[2022-03-27 04:08:24,040] {standard_task_runner.py:77} INFO - Job 31: Subtask format_to_parquet_task
[2022-03-27 04:08:29,281] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-03-27 04:08:29,316] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 1470. PIDs of all processes in the group: [1470]
[2022-03-27 04:08:29,319] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1470
[2022-03-27 04:08:30,259] {process_utils.py:70} INFO - Process psutil.Process(pid=1470, status='terminated', exitcode=0, started='04:08:23') (1470) terminated with exit code 0
